### ISSUE TITLE
[PE-D][Tester D] Syntax of user commands are inconsistent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-4/tp#178]
The interest-related commands are in camel case where as the module-related commands are delimited with white space. E.g., addInt vs mod add.
Moving forward, perhaps the team could standardize to the same format for all commands such that it is easier for users to remember and use them.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: shwene/ped#2

**Comment by sltsheryl** [comment]
@carriezhengjr We can possibly add an explanation why it is designed this way (ie. any commands relating to student information are done through ```add ...```, ```findInt``` and ```addInt``` but we deliberately use the syntax ```mod <command word>``` to distinguish Student commands and Module commands. (Should we place this in UG or DG?)

**Comment by carriezhengjr** [comment]
> @carriezhengjr We can possibly add an explanation why it is designed this way (ie. any commands relating to student information are done through `add ...`, `findInt` and `addInt` but we deliberately use the syntax `mod <command word>` to distinguish Student commands and Module commands. (Should we place this in UG or DG?)

Maybe we can put in UG, before all mod commands, as a `Tip`.

**Comment by sltsheryl** [comment]
> > @carriezhengjr We can possibly add an explanation why it is designed this way (ie. any commands relating to student information are done through `add ...`, `findInt` and `addInt` but we deliberately use the syntax `mod <command word>` to distinguish Student commands and Module commands. (Should we place this in UG or DG?)
> 
> Maybe we can put in UG, before all mod commands, as a `Tip`.

Yes
