### ISSUE TITLE
[PE-D][Tester A] Find command too general

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-4/tp#181]
Find command seems to be too general, user is unable to clearly distinguish the type of keywords he/she is finding for (eg. name vs telegram id).

Example: user wants to find a batchmate with the **name** of john. However, the find command displays Jack as well as his telegram username contains "John" even though this was not the intended result the user is expecting. 
![PE-D-BUG.png](https://raw.githubusercontent.com/24Donovan24/ped/main/files/b17fd476-74b0-4531-8338-617a734793e6.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: 24Donovan24/ped#3

**Comment by sltsheryl** [comment]
It is written in the user guide that under the `find` feature,
`NAME`, `TELEGRAM`, `GITHUB`, `PHONE` and `EMAIL` are searched.

We deliberately made the search scope of the find feature to be broader as searching only through the name would be too narrow. It would be useful for users who want to search based on keyword and not just by name.
