### ISSUE TITLE
[PE-D][Tester A] Inability to undo/mod unmark all

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-4/tp#197]
The application allows user to `mod mark all` which marks all modules of batchmates as taken. However, should a user accidentally runs the command, there is no way for him to **undo** the action or **unmark all**. This can potentially mess up the statuses of the modules of his batchmates.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: 24Donovan24/ped#8

**Comment by sltsheryl** [comment]
@carriezhengjr Instead of deleting the Clear command, we can use an **ALERT** note for ```clear``` and `mod mark``` in the UG? Flash the message in red?
